name: Daily News Digest

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every day at 07:00 UTC
  workflow_dispatch:     # Allows manual trigger from GitHub UI

jobs:
  generate-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Daily News Digest
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python project.py
