name: Daily News Digest

on:
  schedule:
    - cron: '30 0 * * *'  
  workflow_dispatch:     

jobs:
  generate-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Daily News Digest
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          API_KEY: ${{ secrets.API_KEY }}
          MY_MAIL: ${{ secrets.MY_MAIL }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
          
        run: python project.py
